[package]
name = "ray_tracing_in_one_weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33"
derive_more = { version = "1.0", features = ["from", "display", "deref", "deref_mut"] }